### ISSUE TITLE
SocketTimeout Exception when running bundled WebDriver example

### ISSUE THREAD

**Issue by AshwinPrabhuB** [operasoftware/operaprestodriver#72] opened 2012-04-10 07:35 UTC
My code is as below:

```
DesiredCapabilities operaCapabilities = DesiredCapabilities.opera();
operaCapabilities.setCapability("opera.host", "127.0.0.1");
operaCapabilities.setCapability("opera.port", -1);
operaCapabilities.setCapability("opera.profile", "");

OperaDriver driver = new OperaDriver(operaCapabilities);
```

---

This generates an exception as so:

com.opera.core.systems.runner.OperaRunnerException: Timeout waiting for launcher to connect on port 29392
    at com.opera.core.systems.runner.launcher.OperaLauncherRunner.<init>(OperaLauncherRunner.java:159)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:322)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:224)
    at com.test.TestMain.main(TestMain.java:31)
Caused by: java.net.SocketTimeoutException: Accept timed out
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:408)
    at java.net.ServerSocket.implAccept(ServerSocket.java:462)
    at java.net.ServerSocket.accept(ServerSocket.java:430)
    at com.opera.core.systems.runner.launcher.OperaLauncherRunner.<init>(OperaLauncherRunner.java:140)
##     ... 3 more

I can see OperaLauncher icon appear in the system tray and opera also launches with speed dial page. But then I get socket timeout exception. I had set "opera.port" to -1 to force the port to 7001 (as in opera:config developer tools/Proxy Port setting), but still it tries to connect with a random port each time. I am not particular about any port, as long as I can get it to work somehow. 

This seems to be a simple straightforward case, what am I missing?

I am using OperaDriver 0.10 (also tried 0.11 with same result) + Selenium 2.20.0 on Windows 7 with Opera 11.62, Build 1347 and Opera 11.52/Build 110.

Also I had issues with exceptions related to opera launcher not being present in the jar, so I had to download OperaLauncher.exe separately (Is this is cause?).

Thanks,
Ashwin

**Comment by andreastt** [comment] 2012-05-07 09:16
You shouldn't have to do any of these steps when using Opera 11.62.  I believe the problem is fixed in 0.12, though.

**Closed as completed by andreastt** 2012-05-07 09:16 UTC
